version: '3'
services:
  app:
    build:
      context : .
      dockerfile : Dockerfile
    environment:
      DATABASE_URL: postgresql://post:password@database/post_db
    ports:
      - "8080:8000"

  database:
    image: postgres:13.6
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post_db
      POSTGRES_PASSWORD: password
    volumes:
    - ./pg-data:/var/lib/postgresql/data